application:
  kafka:
    topic: "demo-topic"

spring:
  application:
    name:
      demo-producer
  kafka:
    producer:
#      bootstrap-servers: "127.0.0.1:9092"
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
      client-id: "demo-producer"
      acks: all
      enable-idempotence: true

logging:
  file:
    path: logs/demo-producer.log
  level:
    root: info

